spring:
  application:
    name: diamond

  datasource:
    url: jdbc:mysql://localhost:3306/diamond
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: warn

server:
  port: 3333

app:
  url: "http://localhost:5173/"