spring:
  application:
    name: diamond

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/diamond}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: warn

server:
  port: ${PORT:3333}

app:
  url: ${APP_URL:http://localhost:5173/}